package principal1;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.Vector;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author lenovo
 */
public class Main extends javax.swing.JFrame {
    
    DefaultMutableTreeNode Root;
    Vector<String> ListaDirSup=new Vector<String>();
    Vector<String> ListaArchSup=new Vector<String>();
    String localDir;
    public void addHijos(DefaultMutableTreeNode nodo){
        if(nodo.getChildCount()!=0){
            nodo.removeAllChildren();
        }
        Vector<String> ListaDir=new Vector<String>();
        Vector<String> ListaArch=new Vector<String>();
        DefaultMutableTreeNode upNode=(nodo.isRoot())?nodo:(DefaultMutableTreeNode)nodo.getParent();
        String Ruta=nodo.getUserObject().toString();
        while(!upNode.isRoot())
        {
            Ruta=upNode.getUserObject().toString()+"\\"+Ruta;
            upNode=(DefaultMutableTreeNode)upNode.getParent();
        }
 
        try{
            Process sysCall;
            BufferedReader br;
            String s="";
            String  strCmd="cmd /c cd "+localDir+"\\"+Ruta+ " & dir";
            System.out.println(strCmd);
            sysCall=Runtime.getRuntime().exec(strCmd);
            br=new BufferedReader(new InputStreamReader(sysCall.getInputStream()));
            while((s=br.readLine())!=null)
            {
               System.out.println(s);
               int indexArch="                                         ".length();
               if(s.contains("<DIR>")){
                    int indexDir=s.indexOf("<DIR>")+"<DIR>".length()+1;
                    String nomDir=s.substring(indexDir);
                    ListaDir.add(nomDir.trim());
                }

                else{
                    String nomArch=(s.length()>indexArch)?s.substring(indexArch):s;
                    ListaArch.add(nomArch);
                }
            }
            ListaDir=new Vector<String>(ListaDir.subList(2,ListaDir.size()));
            ListaArch=new Vector<String>(ListaArch.subList(5,ListaArch.size()-2));
            int i;
            for(i = 0; i<ListaDir.size();i++){
                DefaultMutableTreeNode hijo=new DefaultMutableTreeNode(ListaDir.get(i).toString());
                nodo.add(hijo);
            }
            for(i = 0; i<ListaArch.size();i++){
                DefaultMutableTreeNode hijo=new DefaultMutableTreeNode(ListaArch.get(i).toString());
                nodo.add(hijo);
            }
            ListaArchSup.addAll(ListaArch);
            ListaDirSup.addAll(ListaDir);
        }catch(Exception e){}
    }
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ArbolArchivos = new JTree(Root);
        addHijos(Root);
        try{
            Process dir=Runtime.getRuntime().exec("cmd /c cd");
            BufferedReader br=new BufferedReader(new InputStreamReader(dir.getInputStream()));
            localDir=br.readLine();
        }catch(Exception e){}

        ArbolArchivos.addTreeSelectionListener(
            new TreeSelectionListener() {
                @Override
                public void valueChanged(TreeSelectionEvent e) {
                    DefaultMutableTreeNode seleccionado=(DefaultMutableTreeNode)ArbolArchivos.getLastSelectedPathComponent();
                    if(ListaDirSup.contains(seleccionado.getUserObject().toString())){
                        addHijos(seleccionado);
                    }
                }
            }
        );
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ArbolArchivos.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                ArbolArchivosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ArbolArchivos);

        jScrollPane2.setViewportView(jTree2);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void ArbolArchivosValueChanged(javax.swing.event.TreeSelectionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JTree ArbolArchivos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree2;
    // End of variables declaration                   
}
